projectKey=itz-prashant_multi-tanent-authentication
sonar.organization=itz-prashant
sonar.projectName=multi-tanent-authentication
sonar.sources=src
sonar.exclusions=**/node_modules/**/*, **/dist/**/*, **/build/**/*, **/migration/**/*
sonar.qualitygate.wait=true
sonar.scm.exclusion.disabled=true